### ISSUE TITLE
Does not work with DST

### ISSUE THREAD

**Issue by shadowhand** [ozziexsh/friendlytimezone#1]
When DST is in effect in the USA or the UK, many of these values will be off-by-one. The offsets should be generated dynamically instead of hard coded.

**Comment by ozziexsh** [comment]
How would you suggest?

**Comment by shadowhand** [comment]
Make the result non-static, so that the offsets are generated at runtime.

**Comment by ozziexsh** [comment]
Lol, I understand that. I was more looking for if you had any suggestions on implementation.

d80b6e3 closes this
